### ISSUE TITLE
Problem with the mod numismatic overhaul on server 1.19.2

### ISSUE THREAD

**Issue by Towergy** [glisco03/numismatic-overhaul#127]
hey i got a problem it doesn't work on server . i'v got a fabric server 1.19.2 install , loader 0.15.1 .

[1.19+] Numismatic Overhaul - 0.2.10 with [1.19] oωo - 0.9.3

Can u help me fix this problem ?
 because i'm building a modpack , Please .

I only install fabric api , numismatic overhaul and owo on the server .

There is the logs :

[00:26:10] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.15.1
[00:26:10] [main/INFO]: Loading 48 mods:
	- fabric-api 0.77.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.42+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.12+def3f86d90
	   |-- fabric-networking-v0 0.3.29+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.1.0+ee641e7390
	   |-- fabric-recipe-api-v1 1.0.2+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.33+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.25+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.28+df3654b390
	   |-- fabric-rendering-v1 1.13.0+526f2c6790
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabricloader 0.15.1
	   \-- mixinextras 0.3.1
	- java 17
	- minecraft 1.19.2
	- numismatic-overhaul 0.2.10+1.19
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- stacc 1.3.4
	- owo 0.9.3+1.19
	   \-- blue_endless_jankson 1.2.1
[00:26:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[00:26:10] [main/INFO]: Compatibility level set to JAVA_16
[00:26:10] [main/INFO]: Compatibility level set to JAVA_17
[00:26:10] [main/WARN]: Error loading class: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage (java.lang.ClassNotFoundException: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage)
[00:26:10] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.1).
[00:26:12] [main/INFO]: Building unoptimized datafixer
[00:26:13] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: FORMAT
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.1.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.0]
Caused by: java.lang.NoSuchFieldError: FORMAT
	at net.minecraft.class_1799.<clinit>(class_1799.java:126) ~[server-intermediary.jar:?]
	at net.minecraft.class_1761.<init>(class_1761.java:114) ~[server-intermediary.jar:?]
	at net.minecraft.class_1761$1.<init>(class_1761.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_1761.<clinit>(class_1761.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792.<init>(class_1792.java:94) ~[server-intermediary.jar:?]
	at net.minecraft.class_1739.<init>(class_1739.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792.method_7867(class_1792.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_2248.method_8389(class_2248.java:554) ~[server-intermediary.jar:?]
	at net.minecraft.class_7143$class_7144.method_41583(class_7143.java:60) ~[server-intermediary.jar:?]
	at net.minecraft.class_7143$class_7144.method_41581(class_7143.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_7143.method_41579(class_7143.java:199) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	... 4 more

**Comment by Kurty00** [comment]
I'm having the same problem...

**Comment by Noaaan** [comment]
This is a somewhat known issue, and is related to stacc - the API/dependency Numismatic includes in order to increase stack sizes beyond 64. While a similar crash was fixed with 0.2.10 (see #113), ~~this was fixed with stacc, but is not shipped with this version of Numismatic~~

**Comment by Noaaan** [comment]
Re-reading the commit history of stacc, this was never backported for <1.19.2

**Comment by Kurty00** [comment]
So, what can we do to use numismatic-overhaul to run on the latest fabric 1.19.2 server?

**Comment by Noaaan** [comment]
Unfortunately there is not a lot that can be done at the moment. I am waiting on a fix from Stacc, and once that is released I will release a fixed version of Numismatic

**Comment by gliscowo** [comment]
The fix for this is available in [0.2.11 for 1.19+](https://modrinth.com/mod/numismatic-overhaul/version/0.2.11+1.19)
Cheers
