### ISSUE TITLE
java.lang.IllegalStateException: Rendersystem called from wrong thread

### ISSUE THREAD

**Issue by ChandelureF-5** [glisco03/numismatic-overhaul#143]
there appears to be an issue with the render system on a thread whenever this mod is installed
[here's the entire log](https://github.com/wisp-forest/numismatic-overhaul/files/15204913/latest.log)
and the section in particular that i'm worried about
```
[13:38:56] [main/WARN]: @Redirect conflict. Skipping stacc.mixins.json:DesktopHandSplayedDuplicationFixin from mod stacc->@Redirect::floor(FLjava/util/Set;ILnet/minecraft/class_1799;)I with priority 1000, already redirected by inventorymod.mixins.json:ScreenHandlerMixin from mod inventorymod->@Redirect::floor(FLjava/util/Set;ILnet/minecraft/class_1799;)I with priority 1000
[13:38:58] [main/WARN]: Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:185) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:174) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:874) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2609) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2580) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[1.20.4-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
```
is there any way to fix this manually, or do i have to wait a bit

**Comment by Noaaan** [comment]
What is `inventorymod`? From the log that seems to be what is causing a conflict

**Comment by ChandelureF-5** [comment]
oh, it's just a thing i decided to add to make my life generally easier
increases stack limit to the 32 bit integer limit

**Comment by ChandelureF-5** [comment]
might be what's breaking the mod, iunno for sure tho

**Comment by ChandelureF-5** [comment]
though it is a general rendersystem error, so it could also be more

**Comment by ChandelureF-5** [comment]
i realize now that this mod in particular incorporates the Stacc API, which might be the source of the rendersystem problem

**Comment by gliscowo** [comment]
I would also suspect that this is simply an incompatibility between stacc and inventorymod - after all, they do the same thing (thus, it also doesn't make sense to have them both). 

I'd suggest simply removing inventorymod and [configuring stacc](https://github.com/Devan-Kerman/stacc#) so that you get the same effect. Let us know if this helps!

Cheers

**Comment by Noaaan** [comment]
I believe this issue should no longer occur, as we use the vanilla stack size component (no longer using Stacc)
