### ISSUE TITLE
Game fails to load

### ISSUE THREAD

**Issue by KevinKharma1** [glisco03/numismatic-overhaul#22]
Hello, I saw this mod on a YouTube video and it looked cool, and when I downloaded it, my Minecraft doesn't load at all. It says it is still loading in the background but I waited probably 10 minutes and it still didn't load. I do have other mods loaded but none of them affect the inventory. I also can't show any crash report since my computer is still "technically" loading the game. Please help.

btw I have version 0.2.1 of the mod

**Comment by tort-oise** [comment]
Close your Minecraft instance with the task manager, then look in your logs folder `(\.minecraft\logs\latest .txt or .log file)` and upload the log. Also, I really recommend you take this to the Discord server, not GitHub issues.

**Comment by KevinKharma1** [comment]
Btw I couldn't find the discord inv link
[12:54:59] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.5
[12:54:59] [main/INFO]: Loading 143 mods:
	- advanced-xray-fabric 1.18.2-1.0.0-build.11
	- ambientenvironment 7.0+19
	- ambientsounds 5.0.16
	- appleskin 2.4.0+mc1.18.2
	- architectury 4.2.50
	- autofish 0.9.4
	- autorun 0.4.0
	- axesareweapons 1.5.1
	- balm-fabric 3.0.0+0
	- bclib 1.4.5
	- blue_endless_jankson 1.2.1 via jankson
	- caffeineconfig 1.1.0 via sodium-extra
	- cardinal-components-base 4.1.3 via numismatic-overhaul
	- cardinal-components-entity 4.1.3 via numismatic-overhaul
	- chesttracker 1.1.13
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.2.57
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-scissors-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- collective-fabric 4.26
	- com_electronwill_night-config_core 3.6.3 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.3 via forgeconfigapiport
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- controlling 9.0+19
	- creativecore 2.6.10
	- dehydration 1.2.8
	- disable_custom_worlds_advice 2.0
	- dynamicfps 2.1.0
	- easiervillagertrading 1.18.2-fabric0.47.10-1.5.4
	- eatinganimationid 1.6
	- enhanced_attack_indicator 1.0.3+1.18
	- environmentz 1.2.2
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via modmenu
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via iris
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via modmenu
	- fabric-screen-api-v1 1.0.10+d882b91560 via modmenu
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabric-tree-chopper 0.8.5
	- fabricloader 0.14.5
	- fiber 0.23.0-2 via collective-fabric
	- fiber2cloth 3.2.0 via fabric-tree-chopper
	- forgeconfigapiport 3.2.0
	- fps 1.18-1.2.1-Fabric
	- gbfabrictools 1.3.4+1.18.2 via easiervillagertrading
	- goosik-config 0.2.0 via visuality
	- grindenchantments 1.6.1+1.18.2
	- grindstonesharpertools-fabric 1.6
	- guiclock-fabric 3.0
	- iceberg 1.0.38
	- impactfulweather 2.4.6
	- interactic 0.1.10+1.18
	- inventoryhud 3.4.2
	- iris 1.2.4-build.38
	- itemborders 1.1.5
	- itemmodelfix 1.0.3+1.18
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- lapisreserve 1.0.8
	- lazydfu 0.1.2
	- legendarytooltips 1.2.4
	- libgui 5.3.1+1.18 via chesttracker
	- libninepatch 1.1.0 via libgui
	- libraryferret 1.0.3
	- lithium 0.7.9
	- malilib 0.12.1
	- minecraft 1.18.2
	- mm 2.3 via shulkerboxtooltip
	- modmanager 1.2.3+1.18
	- modmenu 3.2.2
	- monsters_in_the_closet 1.0.3+1.18
	- notenoughanimations 1.6.0
	- notenoughcrashes 4.1.6+1.18.2
	- numismatic-overhaul 0.2.1+1.18
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- owo-sentinel 0.7.1+1.18 via numismatic-overhaul
	- phosphor 0.8.1
	- reeses-sodium-options 1.4.2
	- roughlyenoughitems 8.0.442
	- shulkerboxtooltip 3.0.7+1.18.2
	- signtools 1.0.0
	- skinlayers 1.4.4-mc1.18.2
	- sleepwarp 1.1.1+1.18.2
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.4+mc1.18.2-build.39
	- stacc 1.3.0 via numismatic-overhaul
	- taxfreelevels 1.3
	- tlcosmetica 0.4.0 via visuality
	- visuality 0.4.2
	- waveycapes 1.2.0
	- whereisit 1.14.10 via chesttracker
[12:55:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/kevin/Library/Application%20Support/minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:55:00] [main/INFO]: Compatibility level set to JAVA_16
[12:55:00] [main/INFO]: Compatibility level set to JAVA_17
[12:55:00] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 0 override(s) found
[12:55:00] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[12:55:00] [main/INFO]: Loaded configuration file for Sodium Extra: 27 options available, 0 override(s) found
[12:55:01] [main/WARN]: Error loading class: io/github/apace100/origins/command/OriginCommand (java.lang.ClassNotFoundException: io/github/apace100/origins/command/OriginCommand)
[12:55:01] [main/WARN]: @Mixin target io.github.apace100.origins.command.OriginCommand was not found dehydration.mixins.json:compat.OriginCommandMixin from mod dehydration
[12:55:01] [main/WARN]: Error loading class: io/github/apace100/origins/component/PlayerOriginComponent (java.lang.ClassNotFoundException: io/github/apace100/origins/component/PlayerOriginComponent)
[12:55:01] [main/WARN]: @Mixin target io.github.apace100.origins.component.PlayerOriginComponent was not found dehydration.mixins.json:compat.PlayerOriginComponentMixin from mod dehydration
[12:55:01] [main/WARN]: Error loading class: io/github/apace100/origins/command/OriginCommand (java.lang.ClassNotFoundException: io/github/apace100/origins/command/OriginCommand)
[12:55:01] [main/WARN]: @Mixin target io.github.apace100.origins.command.OriginCommand was not found environmentz.mixins.json:compat.OriginCommandMixin from mod environmentz
[12:55:01] [main/WARN]: Error loading class: io/github/apace100/origins/component/PlayerOriginComponent (java.lang.ClassNotFoundException: io/github/apace100/origins/component/PlayerOriginComponent)
[12:55:01] [main/WARN]: @Mixin target io.github.apace100.origins.component.PlayerOriginComponent was not found environmentz.mixins.json:compat.PlayerOriginComponentMixin from mod environmentz
[12:55:01] [main/WARN]: Error loading class: me/thonk/croptopia/blocks/LeafCropBlock (java.lang.ClassNotFoundException: me/thonk/croptopia/blocks/LeafCropBlock)
[12:55:01] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[12:55:01] [main/WARN]: Error loading class: me/thonk/croptopia/blocks/LeafCropBlock (java.lang.ClassNotFoundException: me/thonk/croptopia/blocks/LeafCropBlock)
[12:55:01] [main/WARN]: Error loading class: me/thonk/croptopia/blocks/LeafCropBlock (java.lang.ClassNotFoundException: me/thonk/croptopia/blocks/LeafCropBlock)
[12:55:02] [main/WARN]: Error loading class: io/wispforest/owo/network/OwoNetChannel$ClientHandle (java.lang.ClassNotFoundException: io/wispforest/owo/network/OwoNetChannel$ClientHandle)
[12:55:02] [DefaultDispatcher-worker-1/INFO]: Checking for mod updates...
[12:55:04] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod advanced-xray-fabric: No possible match found
[12:55:05] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod ambientenvironment: No possible match found
[12:55:05] [DefaultDispatcher-worker-1/INFO]: No update for ambientsounds found!
[12:55:06] [DefaultDispatcher-worker-1/INFO]: No update for appleskin found!
[12:55:06] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod architectury: null
[12:55:06] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod autofish: null
[12:55:06] [DefaultDispatcher-worker-1/INFO]: No update for autorun found!
[12:55:07] [DefaultDispatcher-worker-1/INFO]: No update for axesareweapons found!
[12:55:07] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod balm-fabric: No possible match found
[12:55:08] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod bclib: No possible match found
[12:55:08] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod chesttracker: No possible match found
[12:55:09] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod cloth-api: No possible match found
[12:55:09] [DefaultDispatcher-worker-1/INFO]: No update for cloth-config found!
[12:55:09] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod collective-fabric: No possible match found
[12:55:09] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod controlling: No possible match found
[12:55:10] [DefaultDispatcher-worker-1/INFO]: No update for creativecore found!
[12:55:10] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod dehydration: No possible match found
[12:55:10] [DefaultDispatcher-worker-1/INFO]: No update for disable_custom_worlds_advice found!
[12:55:11] [DefaultDispatcher-worker-1/INFO]: No update for dynamicfps found!
[12:55:11] [DefaultDispatcher-worker-1/INFO]: No update for easiervillagertrading found!
[12:55:12] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod eatinganimationid: No possible match found
[12:55:12] [DefaultDispatcher-worker-1/INFO]: No update for enhanced_attack_indicator found!
[12:55:12] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod environmentz: No possible match found
[12:55:14] [DefaultDispatcher-worker-1/INFO]: Update for fabric found [0.51.1+1.18.2 -> 0.53.0+1.18.2]
[12:55:15] [DefaultDispatcher-worker-1/INFO]: Update for forgeconfigapiport found [3.2.0 -> v3.0.0-1.18-Fabric]
[12:55:15] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod fps: No possible match found
[12:55:16] [DefaultDispatcher-worker-1/INFO]: No update for grindenchantments found!
[12:55:16] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod grindstonesharpertools-fabric: No possible match found
[12:55:16] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod guiclock-fabric: No possible match found
[12:55:17] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod iceberg: No possible match found
[12:55:17] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod impactfulweather: No possible match found
[12:55:17] [DefaultDispatcher-worker-1/INFO]: No update for interactic found!
[12:55:17] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod inventoryhud: No possible match found
[12:55:17] [DefaultDispatcher-worker-1/INFO]: No update for iris found!
[12:55:18] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod itemborders: No possible match found
[12:55:18] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod itemmodelfix: No possible match found
[12:55:18] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod lapisreserve: No possible match found
[12:55:18] [DefaultDispatcher-worker-1/INFO]: No update for lazydfu found!
[12:55:19] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod legendarytooltips: No possible match found
[12:55:19] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod libraryferret: No possible match found
[12:55:19] [DefaultDispatcher-worker-1/INFO]: No update for lithium found!
[12:55:20] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod malilib: No possible match found
[12:55:20] [DefaultDispatcher-worker-1/INFO]: No update for modmanager found!
[12:55:20] [DefaultDispatcher-worker-1/INFO]: No update for modmenu found!
[12:55:21] [DefaultDispatcher-worker-1/INFO]: No update for monsters_in_the_closet found!
[12:55:21] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod notenoughanimations: No possible match found
[12:55:21] [DefaultDispatcher-worker-1/INFO]: No update for notenoughcrashes found!
[12:55:22] [DefaultDispatcher-worker-1/INFO]: No update for numismatic-overhaul found!
[12:55:22] [DefaultDispatcher-worker-1/INFO]: No update for phosphor found!
[12:55:22] [DefaultDispatcher-worker-1/INFO]: No update for reeses-sodium-options found!
[12:55:22] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod roughlyenoughitems: No possible match found
[12:55:23] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod shulkerboxtooltip: No possible match found
[12:55:23] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod signtools: No possible match found
[12:55:23] [DefaultDispatcher-worker-1/INFO]: No update for skinlayers found!
[12:55:24] [DefaultDispatcher-worker-1/INFO]: No update for sleepwarp found!
[12:55:24] [DefaultDispatcher-worker-1/INFO]: No update for sodium found!
[12:55:24] [DefaultDispatcher-worker-1/INFO]: No update for sodium-extra found!
[12:55:24] [DefaultDispatcher-worker-1/INFO]: No update for taxfreelevels found!
[12:55:25] [DefaultDispatcher-worker-1/INFO]: No update for visuality found!
[12:55:25] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod waveycapes: No possible match found
[12:55:26] [DefaultDispatcher-worker-1/WARN]: Error loading class: io/wispforest/owo/ops/ItemOps (java.lang.ClassNotFoundException: io/wispforest/owo/ops/ItemOps)
[12:55:26] [DefaultDispatcher-worker-1/ERROR]: Uncaught exception in thread "DefaultDispatcher-worker-1"
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1657 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.5.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at xyz.deathsgun.modmanager.update.UpdateManager$checkUpdates$2.invokeSuspend(UpdateManager.kt:92) ~[modmanager-1.2.3+1.18.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-1.6.21-bd27c6366035e89b.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at xyz.deathsgun.modmanager.update.UpdateManager.checkUpdates(UpdateManager.kt:72) ~[modmanager-1.2.3+1.18.jar:?]
	at xyz.deathsgun.modmanager.PreLaunchHook$onPreLaunch$1.invokeSuspend(PreLaunchHook.kt:40) ~[modmanager-1.2.3+1.18.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [org_jetbrains_kotlin_kotlin-stdlib-1.6.21-bd27c6366035e89b.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.5.jar:?]
	... 21 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for numismatic-overhaul.mixins.json:ServerPlayerEntityMixin from mod numismatic-overhaul during activity: [Transform -> Method onServerDeath(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKESTATIC -> io/wispforest/owo/ops/ItemOps::singleCopy:(Lnet/minecraft/class_1799;)Lnet/minecraft/class_1799;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.5.jar:?]
	... 21 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.wispforest.owo.ops.ItemOps
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.5.jar:?]
	... 21 more
Caused by: java.lang.ClassNotFoundException: io.wispforest.owo.ops.ItemOps
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.5.jar:?]
	... 21 more

**Comment by BasiqueEvangelist** [comment]
You need to install [oωo-lib](https://www.curseforge.com/minecraft/mc-mods/owo-lib).

**Comment by tort-oise** [comment]
👽

**Comment by KevinKharma1** [comment]
Ok I did it and it works, thank you guys :)
