### ISSUE TITLE
Fabric 1.19 error log

### ISSUE THREAD

**Issue by MrJorman** [glisco03/numismatic-overhaul#34]
```[16:53:01] [Server thread/ERROR]: Error executing task on Server
java.lang.IllegalArgumentException: Sell Stack must not be empty
        at com.glisco.numismaticoverhaul.block.ShopOffer.<init>(ShopOffer.java:22) ~[numismatic-overhaul-0.2.3+1.19.jar:?]
        at com.glisco.numismaticoverhaul.block.ShopScreenHandler.createOffer(ShopScreenHandler.java:108) ~[numismatic-overhaul-0.2.3+1.19.jar:?]
        at com.glisco.numismaticoverhaul.network.ShopScreenHandlerRequestC2SPacket.handle(ShopScreenHandlerRequestC2SPacket.java:20) ~[numismatic-overhaul-0.2.3+1.19.jar:?]
        at io.wispforest.owo.network.OwoNetChannel.lambda$new$0(OwoNetChannel.java:131) ~[owo-lib-0.7.3+1.19.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.redirect$zic000$redirectExecuteTask(class_1255.java:521) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:15772) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zlj000$modifiedRunLoop(MinecraftServer.java:3889) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]```

**Comment by Noaaan** [comment]
I have yet to look into this issue. Is it re-producable?

**Comment by gliscowo** [comment]
This error, while sometimes logged on the server, is not fatal and is soon to be fixed in the next version of Numismatic. As such, I'll go ahead and close this
Cheers
